"""sync latest model changes

Revision ID: 11d292bc19a8
Revises: 2c777d424c03
Create Date: 2026-05-29 10:48:17.003590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11d292bc19a8'
down_revision: Union[str, Sequence[str], None] = '2c777d424c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'created_id')
    op.add_column('workspaces', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_column('workspaces', 'organization_id')
    op.add_column('users', sa.Column('created_id', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
