"""add tenant columns to approvals documents

Revision ID: 1c422ba90a98
Revises: 164922c6bfff
Create Date: 2026-06-02 17:06:47.199458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c422ba90a98'
down_revision: Union[str, Sequence[str], None] = '164922c6bfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_column('documents', 'organization_id')
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_index(op.f('ix_approval_requests_organization_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'organization_id')
    # ### end Alembic commands ###
