"""fix departments workspaces subscription sqlalchemy2 cleanup

Revision ID: 2c777d424c03
Revises: 8acab5860c49
Create Date: 2026-05-26 16:46:43.612787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c777d424c03'
down_revision: Union[str, Sequence[str], None] = '8acab5860c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_org_status', 'subscriptions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_order_id'), 'subscriptions', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_payment_id'), 'subscriptions', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_subscription_id'), 'subscriptions', ['razorpay_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_index(op.f('ix_auditlog_id'), table_name='audit_log')
    op.create_index('ix_auditlog_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_auditlog_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_auditlog_user_id', 'audit_log', ['user_id'], unique=False)
    op.add_column('departments', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'organizations', ['organization_id'], ['id'])
    op.add_column('tasks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("""UPDATE users SET created_at = NOW() WHERE created_at IS NULL""")
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column("users","created_at",existing_type=sa.DateTime(timezone=True), nullable=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'created_id')
    op.add_column('workspaces', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_column('workspaces', 'organization_id')
    op.add_column('users', sa.Column('created_id', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_column('tasks', 'organization_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_column('departments', 'organization_id')
    op.drop_index('ix_auditlog_user_id', table_name='audit_log')
    op.drop_index('ix_auditlog_entity', table_name='audit_log')
    op.drop_index('ix_auditlog_created_at', table_name='audit_log')
    op.create_index(op.f('ix_auditlog_id'), 'audit_log', ['id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_payment_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_razorpay_order_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index('ix_subscription_org_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
