"""initial tables

Revision ID: 4e2a81f0a7fe
Revises: 
Create Date: 2026-05-04 00:31:56.445091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e2a81f0a7fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apphist_id'), table_name='approval_hostory')
    op.drop_table('approval_hostory')
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('documents_ibfk_3'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_ibfk_1'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'approval_requests', ['approval_request_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'uplaoded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uplaoded_by', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ibfk_1'), 'documents', 'users', ['uplaoded_by'], ['id'])
    op.create_foreign_key(op.f('documents_ibfk_3'), 'documents', 'users', ['approval_request_id'], ['id'])
    op.drop_column('documents', 'uploaded_by')
    op.create_table('approval_hostory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('approval_request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('acted_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acted_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], name=op.f('approval_hostory_ibfk_2')),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('approval_hostory_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_apphist_id'), 'approval_hostory', ['id'], unique=False)
    # ### end Alembic commands ###
