"""add subscription plan limits

Revision ID: 6bfbe955cfae
Revises: 1c422ba90a98
Create Date: 2026-06-03 03:49:53.739292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfbe955cfae'
down_revision: Union[str, Sequence[str], None] = '1c422ba90a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('max_storage_mb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'max_storage_mb')
    op.drop_column('subscriptions', 'max_users')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
